export const SHOW_CARDS_LOADER = 'CARDS_LIST/SHOW_CARDS_LOADER';
export const HIDE_CARDS_LOADER = 'CARDS_LIST/HIDE_CARDS_LOADER';
export const LOAD_CARDS_LIST_SUCCESS = 'CARDS_LIST/LOAD_SUCCESS';
export const CHANGE_LIMIT = 'CARDS_LIST/CHANGE_LIMIT';
