export const SHOW_MODAL_POSTS = 'MODAL/SHOW_MODAL_POSTS';
export const HIDE_MODAL_POSTS = 'MODAL/HIDE_MODAL_POSTS';

export const SHOW_MODAL_EDIT = 'MODAL/SHOW_MODAL_EDIT';
export const HIDE_MODAL_EDIT = 'MODAL/HIDE_MODAL_EDIT';
