export const LOAD_POST_COMMENTS = 'COMMENTS/LOAD_POST_COMMENTS';
export const SHOW_COMMENTS_LOADER = 'COMMENTS/SHOW_COMMENTS_LOADER';
export const HIDE_COMMENTS_LOADER = 'COMMENTS/HIDE_COMMENTS_LOADER';
