export const SHOW_POSTS_LOADER = 'USERS_POSTS/SHOW_POSTS_LOADER';
export const HIDE_POSTS_LOADER = 'USERS_POSTS/HIDE_POSTS_LOADER';
export const LOAD_USERS_POST_SUCCESS = 'USERS_POSTS/LOAD_USERS_POST_SUCCESS';
export const LOAD_USER_POSTS_BY_ID = 'USERS_POSTS/LOAD_USER_POSTS_BY_ID';
